import Head from "next/head";

import styles from "../styles/Home.module.css";

import SuperGymProLayout from "../components/layout/SuperGymProLayout";
import HeaderPages from "../components/ui/HeaderPages";
import TitlePages from "../components/ui/TitlePages";
import SectionPages from "../components/ui/SectionPages";
import ContainerPages from "../components/ui/ContainerPages";
import IconService from "../components/ui/IconService";
import NavDesktop from "../components/layout/nav/NavDesktop";
import MenuBar from "../components/ui/MenuBar";

export default function Compromiso() {
  return (
    <div>
      <Head>
        <title>Compromiso</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavDesktop />
      <MenuBar className="only-mobile" nonGradient />
      <HeaderPages frontPage="compromiso" nonMenuBar>
        <div className="flex-center">
          <h2 className={`${styles.title} highlighted`}>COMPROMISO</h2>
        </div>
      </HeaderPages>

      <SectionPages pt="80px">
        <ContainerPages ai="end">
          <IconService image="compromiso_negro.png" />
        </ContainerPages>
        <ContainerPages>
          <TitlePages>Nuestro compromiso</TitlePages>
        </ContainerPages>
        <p>
          Nuestra misión es cuidar nuestro vínculo, que encuentres garantía de
          satisfacción en nuestros servicios. Para esto, definimos un plan que
          une varios servicios en uno.
        </p>
        <p>
          Garantía: Cada equipo tiene el respaldo provisto por la marca, que se
          extiende por un plazo mínimo de 24 meses. Nosotros nos encargamos de
          respaldar ese plazo de manera oficial.
        </p>
        <p>
          Asesoramiento Post Venta: Ante cualquier duda o inconveniente que te
          pueda surgir respecto al uso de los equipos, vamos a estar ahí para
          responderte.
        </p>
        <p>
          Mantenimiento y soporte: Contamos con el taller más completo de
          Uruguay para equipos de Fitness, sea cual sea el problema, nosotros
          podemos encontrar la solución.
        </p>
      </SectionPages>
    </div>
  );
}

Compromiso.Layout = SuperGymProLayout;
