import Head from "next/head";
import styles from "../styles/Home.module.css";
import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined";
import SuperGymProLayout from "../components/layout/SuperGymProLayout";
import BoxContentPage from "../components/ui/BoxContentPage";
import HeaderPages from "../components/ui/HeaderPages";
import TitlePages from "../components/ui/TitlePages";
import NavDesktop from "../components/layout/nav/NavDesktop";
import MenuBar from "../components/ui/MenuBar";

export default function Service() {
  return (
    <div>
      <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavDesktop />
      <MenuBar className="only-mobile" nonGradient />
      <HeaderPages frontPage="servicios" nonMenuBar />

      <section className={`${styles.padding60} ${styles.contentPages}`}>
        <BoxContentPage>
          <TitlePages>
            Servicio y soporte <SettingsOutlinedIcon className="text-primary" />
          </TitlePages>
          <p>
            Cuando invierte en nuestros equipos, nosotros invertimos en usted.
            Somos tan buenos como la reputación que tenemos con usted y sus
            miembros. Desde la programación de la instalación hasta preguntas
            sobre piezas y reemplazos, estamos aquí para responder sus preguntas
            y mantener sus equipos en óptimas condiciones.
          </p>
          <p>
            Nuestros consultores de servicio y soporte están aquí para usted de
            lunas a viernes de 9:00 a 18:00 hs. y sábados de 10:00 a 14:00 hs.
            Fuera del horario de atención, comuníquese con nosotros y le
            responderemos el siguiente día hábil.
          </p>
        </BoxContentPage>
      </section>
    </div>
  );
}

Service.Layout = SuperGymProLayout;
